[project]
name = "teammarusya"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "kagglehub>=0.3.13",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
